### ISSUE TITLE
Fix the demo project

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#76]
For some reason the demo project's got 2 button bars and I can't type more than one character in the input. That's really weird.

![image](https://i.imgur.com/bwoIZmB.png)

**Comment by andrerpena** [comment]
I'm working on it

**Comment by andrerpena** [comment]
@danigomez or @JonatanSalas Did you make any change that you think might be making the input to lose focus when you type in the default demo?

**Comment by andrerpena** [comment]
For some reason the Bootstrap-UI demo works but the default one doesn't

**Comment by JonatanSalas** [comment]
@andrerpena I will take a look, this is a stranger thing :disappointed_relieved:

**Comment by andrerpena** [comment]
Thanks. No exception is being triggered, I can't continue with #18 until this is fixed. 
It seems to me that you or @danigomez introduced something new and you fixed it on Bootstrap but forgot about the demo and now I don't have any idea why it isn't working. I'm investigating for 30 minutes now.

**Comment by andrerpena** [comment]
Still tracking the problem but it seems that the problem goes away if I stop using @danigomez Root component.

This is the `AutoFormInternal.render` that works:

![https://i.imgur.com/l7KsDRI.png](https://i.imgur.com/l7KsDRI.png)

**Comment by JonatanSalas** [comment]
This is strange :/ we are using the version released with tag experimental and they work really well with the @danigomez Root Component

**Comment by danigomez** [comment]
@andrerpena, i just fixed it, i will commit the change! :smile:

**Comment by andrerpena** [comment]
Doooontt.. I just did it

**Comment by andrerpena** [comment]
The problem is that the root component cannot be stateless

**Comment by andrerpena** [comment]
I appreciate your time fixing it.

**Comment by andrerpena** [comment]
The only thing I still don't quite understand is why the root component can't be stateless :cry:

**Comment by andrerpena** [comment]
Oh I **think** I know now. Stateless components are **always** rerendered when the props change. When you rerender the entire form, all component automatically lose focus. And that was happening when you change any field.
